[project]
name = "week4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "jina>=3.34.0",
    "openai==0.28",
    "sentence-transformers>=5.1.1",
]
